### ISSUE TITLE
双击第一层的cell2次，程序会崩溃

### ISSUE THREAD

**Issue by xb2342996** [seedante/ExploreAlbumOpenAnimation#1]
双击第一层的cell2次，程序会崩溃,EXC_BAD_INSTRUCTION ,提示错误fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by seedante** [comment]
源头找到了，因为在点击 cell 是调用 didSelectCellXXX这个方法，这里赋值了 selectedIndexPath 这个在 extension 里添加的关联对象，这是个强制解析值(使用!修饰)，但目前不清楚为何在第二次点击后这个属性成了空值 nil，目前还在排查中。话说，我真没想到会被点击两次的，我考虑得还不够。

**Comment by xb2342996** [comment]
巧合，我点两次是因为模拟器卡了一下没反应

**Comment by seedante** [comment]
居然这么巧，刚才找到了解决这个问题的取巧办法，点击后暂时 collectionView 的选择功能，然后在 push 之后恢复。

```
    self.selectedIndexPath = indexPath
    self.collectionView?.allowsSelection = false
    ......
    self.navigationController?.pushViewController(albumVC, animated: true)
    self.collectionView?.allowsSelection = true
```

刚才这个 bug 让我看到我的代码还有很多问题，就是尽量不要用强制解析值(!)，我想想怎么改把这个问题彻底解决。
